markdown: kramdown
kramdown:
  input: GFM
permalink: /:year/:month/:title
title: 东篱茶馆
url: http://tanwubin.github.io
subscribe: http://tanwubin.github.io/feed
exclude: [ README.md, newpost.rb ]
domain: tanwubin.github.io
author: tanwubin
email: brieftime@icloud.com
safe: true
excerpt_separator: "&nbsp;"
highlight: true
