markdown: kramdown
kramdown:
  input: GFM
permalink: /:year/:month/:title
title: 小团菜
url: http://xiaotuancai.github.io
subscribe: http://xiaotuancai.github.io/feed
exclude: [ README.md, newpost.rb ]
domain: xiaotuancai.github.io
author: xiaotuancai
email: litwer@126.com
safe: true
excerpt_separator: "&nbsp;"
highlight: true
